export const BRAND_OWNER_ROLE_ID = 'neup_account.brand_owner';
export const BRAND_OWNER_ROLE_NAME = 'neup_account.brand_owner';

export const BRAND_OWNER_PERMISSION_NAMES = [
  'brand.profile.view',
  'brand.profile.edit',
  'brand.settings.view',
  'brand.settings.edit',
  'brand.members.view',
  'notification.read',
  'notification.delete',
  'access.view',
  'access.team.view',
  'access.team.add',
  'access.team.remove',
  'access.connection.view',
  'access.connection.create.brand',
  'access.application.view',
  'account.brand.members.manage',
  'linked_accounts.brand.view',
  'linked_accounts.brand.manage',
  'linked_accounts.brand.manager',
  'account.brand.kyc.view',
  'account.brand.kyc.submit',
  'brand.platforms.view',
  'brand.platforms.manage',
  'data.agreed_terms.view',
  'data.delete_account.start',
  'data.deactivate_account.start',
  'data.materialization.view',
  'data.materialization.modify',
  'security.recent_activities.view',
  'payment.method.show',
  'payment.transactions.show',
  'payment.subscriptions.show',
  'payment.purchase_neup_pro.view',
  'application.view',
  'account.brand.delete',
] as const;

export const BRAND_ROOT_PERMISSION_NAMES = [
  'account.brand.delete',
  'account.brand.kyc.submit',
  'account.brand.kyc.view',
  'account.brand.members.manage',
] as const;
