import {
  ACCESS_ACCOUNT_BRAND_CREATE_PERMISSIONS,
  ACCESS_ACCOUNT_DEPENDENT_CREATE_PERMISSIONS,
  ACCESS_ACCOUNTS_SWITCH_PERMISSIONS,
  ACCESS_LINKED_ACCOUNT_VIEW_PERMISSIONS,
} from '@/logica/account/access-view-permissions';

export const LINKED_ACCOUNT_PERMISSION_GROUPS = {
  brand: [
    ...ACCESS_LINKED_ACCOUNT_VIEW_PERMISSIONS,
    ...ACCESS_ACCOUNT_BRAND_CREATE_PERMISSIONS,
    ...ACCESS_ACCOUNTS_SWITCH_PERMISSIONS,
    'linked_accounts.brand.manage',
    'linked_accounts.brand.manager',
  ],
  dependent: [
    ...ACCESS_LINKED_ACCOUNT_VIEW_PERMISSIONS,
    ...ACCESS_ACCOUNT_DEPENDENT_CREATE_PERMISSIONS,
    ...ACCESS_ACCOUNTS_SWITCH_PERMISSIONS,
  ],
} as const;

export const LINKED_ACCOUNT_NAV_PERMISSIONS = Array.from(
  new Set(Object.values(LINKED_ACCOUNT_PERMISSION_GROUPS).flat()),
);
